version: 2
formats:
    - htmlzip
    - pdf
build:
    os: ubuntu-22.04
    apt_packages:
        - libmpc-dev
        - gcc
    tools:
        python: "3"
python:
    install:
        - method: pip
          path: .
          extra_requirements:
              - docs
sphinx:
    fail_on_warning: true
    configuration: docs/conf.py
